<?php
require_once __DIR__.'/../../backend/shared/auth.php'; require_role('doctor');
require_once __DIR__.'/../../backend/shared/ai_engine.php'; require_once __DIR__.'/../../backend/shared/layout.php';
$hn=$_GET['hn']??$_POST['hn']??''; $st=db()->prepare('SELECT * FROM patients WHERE hn=?'); $st->execute([$hn]); $p=$st->fetch(); if(!$p){exit('ไม่พบ HN');}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $pdo=db(); $pdo->beginTransaction();
  $surgery=isset($_POST['surgery_flag'])?1:0; $major=isset($_POST['major_surgery_flag'])?1:0;
  $st=$pdo->prepare('INSERT INTO visits(patient_id,visit_date,hospital_name,visit_type,department,ward,bed_no,doctor_name,chief_complaint,diagnosis,symptom_note,surgery_flag,major_surgery_flag,surgery_detail,anesthesia_type,sbp,dbp,pulse,temperature,spo2,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  $st->execute([$p['id'],$_POST['visit_date'],$_POST['hospital_name'],$_POST['visit_type'],$_POST['department'],$_POST['ward'],$_POST['bed_no'],$_POST['doctor_name'],$_POST['chief_complaint'],$_POST['diagnosis'],$_POST['symptom_note'],$surgery,$major,$_POST['surgery_detail'],$_POST['anesthesia_type'],$_POST['sbp'],$_POST['dbp'],$_POST['pulse'],$_POST['temperature'],$_POST['spo2'],$_SESSION['user']['id']]);
  $vid=$pdo->lastInsertId();
  $pdo->prepare('INSERT INTO treatments(visit_id,treatment_type,detail,outcome_note) VALUES(?,?,?,?)')->execute([$vid,$_POST['treatment_type'],$_POST['treatment_detail'],$_POST['outcome_note']]);
  foreach(($_POST['med_name']??[]) as $idx=>$name){ if(trim($name)!=='') $pdo->prepare('INSERT INTO medications(visit_id,drug_name,dose,route,frequency,duration,note) VALUES(?,?,?,?,?,?,?)')->execute([$vid,$name,$_POST['med_dose'][$idx]??'',$_POST['med_route'][$idx]??'',$_POST['med_frequency'][$idx]??'',$_POST['med_duration'][$idx]??'',$_POST['med_note'][$idx]??'']); }
  foreach(($_POST['inj_name']??[]) as $idx=>$name){ if(trim($name)!=='') $pdo->prepare('INSERT INTO injections(visit_id,injection_name,dose,route,note) VALUES(?,?,?,?,?)')->execute([$vid,$name,$_POST['inj_dose'][$idx]??'',$_POST['inj_route'][$idx]??'',$_POST['inj_note'][$idx]??'']); }
  if(trim($_POST['vaccine_name']??'')!=='') $pdo->prepare('INSERT INTO vaccines(visit_id,vaccine_name,dose_no,lot_no,injection_date,note) VALUES(?,?,?,?,?,?)')->execute([$vid,$_POST['vaccine_name'],$_POST['vaccine_dose_no'],$_POST['vaccine_lot_no'],$_POST['visit_date'],$_POST['vaccine_note']]);
  if(trim($_POST['appointment_date']??'')!=='') $pdo->prepare('INSERT INTO appointments(patient_id,visit_id,appointment_date,department,doctor_name,reason) VALUES(?,?,?,?,?,?)')->execute([$p['id'],$vid,$_POST['appointment_date'],$_POST['appointment_department'],$_POST['appointment_doctor'],$_POST['appointment_reason']]);
  if(trim($_POST['hba1c']??'')!=='' || trim($_POST['fpg']??'')!=='' || trim($_POST['bmi']??'')!=='' || trim($_POST['sbp']??'')!==''){
    $pdo->prepare('INSERT INTO diabetes_followups(patient_id,visit_id,followup_date,diabetes_type,hba1c,fpg,c_peptide,sbp,dbp,bmi,ldl,hdl,tg,egfr,uacr,metformin,insulin,glp1,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$p['id'],$vid,$_POST['visit_date'],$_POST['diabetes_type'],$_POST['hba1c'] ?: null,$_POST['fpg'] ?: null,$_POST['c_peptide'] ?: null,$_POST['sbp'] ?: null,$_POST['dbp'] ?: null,$_POST['bmi'] ?: null,$_POST['ldl'] ?: null,$_POST['hdl'] ?: null,$_POST['tg'] ?: null,$_POST['egfr'] ?: null,$_POST['uacr'] ?: null,isset($_POST['metformin'])?1:0,isset($_POST['insulin'])?1:0,isset($_POST['glp1'])?1:0,$_POST['diabetes_note']]);
  }
  save_ai_risk((int)$p['id']);
  $pdo->commit(); header('Location: patient-profile.php?hn='.urlencode($p['hn'])); exit;
}
app_header('เพิ่มการรักษา '.$p['hn'],'doctor','dashboard'); ?>
<a class="back" href="patient-profile.php?hn=<?=urlencode($p['hn'])?>">← กลับข้อมูลผู้ป่วย</a>
<form method="post" class="form-stack"><input type="hidden" name="hn" value="<?=e($p['hn'])?>">
<div class="card"><h3>1) Visit / แพทย์ / แผนก</h3><div class="row">
  <div class="field"><label>วันที่รับบริการ</label><input type="date" name="visit_date" value="<?=date('Y-m-d')?>" required></div>
  <div class="field"><label>โรงพยาบาล</label><input name="hospital_name" value="USE MED Hospital"></div>
  <div class="field"><label>ประเภทผู้ป่วย</label><select name="visit_type"><option>OPD</option><option>IPD</option><option>ER</option><option>Telemedicine</option></select></div>
  <div class="field"><label>แผนกที่รับบริการ</label><select name="department"><option>อายุรกรรม</option><option>คลินิกเบาหวาน</option><option>ศัลยกรรมทั่วไป</option><option>วิสัญญี</option><option>สูติ-นรีเวช</option><option>ICU</option><option>ER</option></select></div>
  <div class="field"><label>Ward</label><input name="ward" placeholder="เช่น Ward อายุรกรรม / ICU / OR"></div>
  <div class="field"><label>Bed No.</label><input name="bed_no"></div>
  <div class="field"><label>แพทย์ที่ดูแลรอบนี้</label><input name="doctor_name" value="<?=e($_SESSION['user']['name'])?>"></div>
</div></div>
<div class="card"><h3>2) อาการ/วินิจฉัย/การรักษา</h3><div class="row">
  <div class="field"><label>มาโรงพยาบาลเพราะอะไร</label><textarea name="chief_complaint" required></textarea></div>
  <div class="field"><label>วินิจฉัย/ป่วยอะไร</label><textarea name="diagnosis"></textarea></div>
  <div class="field"><label>ประวัติหรืออาการเพิ่มเติม</label><textarea name="symptom_note"></textarea></div>
  <div class="field"><label>แผนการรักษา</label><select name="treatment_type"><option>ปรับยา</option><option>ติดตามอาการ</option><option>ส่งตรวจเพิ่มเติม</option><option>ผ่าตัด/หัตถการ</option><option>ให้วัคซีน</option><option>ให้ยาฉีด</option></select><textarea name="treatment_detail" placeholder="รายละเอียดการรักษา"></textarea></div>
  <div class="field"><label>ผลลัพธ์/คำแนะนำ</label><textarea name="outcome_note"></textarea></div>
</div><div class="chips"><label class="chip-check"><input type="checkbox" name="surgery_flag"><span>มีการผ่าตัด</span></label><label class="chip-check"><input type="checkbox" name="major_surgery_flag"><span>ผ่าตัดใหญ่</span></label></div><div class="row"><div class="field"><label>รายละเอียดผ่าตัด</label><textarea name="surgery_detail"></textarea></div><div class="field"><label>วิสัญญี</label><select name="anesthesia_type"><option></option><option>General anesthesia</option><option>Spinal anesthesia</option><option>Local anesthesia</option><option>Sedation</option></select></div></div></div>
<div class="card highlight-card"><h3>3) ช่องกรอก AI Clinical Inputs — แยกชัดเจน</h3><div class="section-note">กรอก HbA1c / FPG / BP / BMI แยกช่อง เพื่อให้ AI วิเคราะห์เบาหวานและความดันจากข้อมูลล่าสุดได้ทันทีหลังบันทึก</div>
  <div class="clinical-grid">
    <div class="clinical-card"><strong>HbA1c (%)</strong><input name="hba1c" step="0.1" type="number" placeholder="เช่น 8.2"><small>ค่าคุมเบาหวานระยะยาว</small></div>
    <div class="clinical-card"><strong>FPG (mg/dL)</strong><input name="fpg" step="0.1" type="number" placeholder="เช่น 145"><small>น้ำตาลอดอาหาร</small></div>
    <div class="clinical-card"><strong>BP: SBP / DBP</strong><div class="row" style="grid-template-columns:1fr 1fr;gap:8px"><input name="sbp" type="number" placeholder="SBP"><input name="dbp" type="number" placeholder="DBP"></div><small>ความดันโลหิต</small></div>
    <div class="clinical-card"><strong>BMI</strong><input name="bmi" step="0.1" value="<?=e($p['bmi'])?>"><small>คำนวณ/กรอกล่าสุด</small></div>
  </div>
  <h4>Lab เพิ่มเติมสำหรับติดตามระยะยาว</h4><div class="row"><div class="field"><label>ชนิดเบาหวาน</label><select name="diabetes_type"><option>Type 2</option><option>Type 1</option><option>GDM</option><option>Unknown</option></select></div><div class="field"><label>C-peptide</label><input name="c_peptide" step="0.01" type="number"></div><div class="field"><label>LDL</label><input name="ldl" step="0.1" type="number"></div><div class="field"><label>HDL</label><input name="hdl" step="0.1" type="number"></div><div class="field"><label>TG</label><input name="tg" step="0.1" type="number"></div><div class="field"><label>eGFR</label><input name="egfr" step="0.1" type="number"></div><div class="field"><label>UACR</label><input name="uacr" step="0.1" type="number"></div><div class="field"><label>Pulse</label><input name="pulse" type="number"></div><div class="field"><label>Temp</label><input name="temperature" step="0.1" type="number"></div><div class="field"><label>SpO2</label><input name="spo2" type="number"></div></div>
  <div class="chips"><label class="chip-check"><input type="checkbox" name="metformin"><span>Metformin</span></label><label class="chip-check"><input type="checkbox" name="insulin"><span>Insulin</span></label><label class="chip-check"><input type="checkbox" name="glp1"><span>GLP-1</span></label></div><div class="field"><label>หมายเหตุเบาหวาน/ความดัน</label><textarea name="diabetes_note"></textarea></div>
</div>
<div class="card"><h3>4) ยา / ยาฉีด / วัคซีน / นัดติดตาม</h3><h4>ยา</h4><div id="meds"><div class="row"><div class="field"><input name="med_name[]" placeholder="ชื่อยา"></div><div class="field"><input name="med_dose[]" placeholder="ขนาดยา"></div><div class="field"><input name="med_route[]" placeholder="Route"></div><div class="field"><input name="med_frequency[]" placeholder="ความถี่"></div><div class="field"><input name="med_duration[]" placeholder="ระยะเวลา"></div><div class="field"><input name="med_note[]" placeholder="หมายเหตุ"></div></div></div><h4>ยาฉีด</h4><div class="row"><div class="field"><input name="inj_name[]" placeholder="ชื่อยาฉีด"></div><div class="field"><input name="inj_dose[]" placeholder="ขนาด"></div><div class="field"><input name="inj_route[]" placeholder="Route"></div><div class="field"><input name="inj_note[]" placeholder="หมายเหตุ"></div></div><h4>วัคซีน</h4><div class="row"><div class="field"><input name="vaccine_name" placeholder="ชื่อวัคซีน"></div><div class="field"><input name="vaccine_dose_no" placeholder="เข็มที่"></div><div class="field"><input name="vaccine_lot_no" placeholder="Lot"></div><div class="field"><input name="vaccine_note" placeholder="หมายเหตุ"></div></div><h4>นัดติดตาม</h4><div class="row"><div class="field"><label>วันนัด</label><input type="date" name="appointment_date"></div><div class="field"><label>แผนกนัด</label><input name="appointment_department" placeholder="แผนกนัด"></div><div class="field"><label>แพทย์นัด</label><input name="appointment_doctor" placeholder="แพทย์นัด"></div><div class="field"><label>เหตุผลนัด</label><input name="appointment_reason" placeholder="เหตุผลนัด"></div></div><div class="actions"><button class="btn">บันทึกลงฐานข้อมูลจริง + วิเคราะห์ AI</button><a class="btn secondary" href="patient-profile.php?hn=<?=urlencode($p['hn'])?>">ยกเลิก</a></div></div>
</form><?php app_footer(); ?>