<?php require_once __DIR__.'/../../backend/shared/auth.php'; require_role('doctor'); require_once __DIR__.'/../../backend/shared/layout.php';
$pdo=db(); $q=trim($_GET['hn']??'');
if($q){$st=$pdo->prepare('SELECT * FROM patients WHERE hn LIKE ? OR first_name LIKE ? OR last_name LIKE ? ORDER BY hn LIMIT 30');$st->execute(["%$q%","%$q%","%$q%"]);} else {$st=$pdo->query('SELECT * FROM patients ORDER BY id DESC LIMIT 20');}
$patients=$st->fetchAll(); $stats=['patients'=>$pdo->query('SELECT COUNT(*) FROM patients')->fetchColumn(),'visits'=>$pdo->query('SELECT COUNT(*) FROM visits')->fetchColumn(),'high'=>$pdo->query("SELECT COUNT(*) FROM ai_risk_assessments a JOIN (SELECT patient_id,MAX(id) mid FROM ai_risk_assessments GROUP BY patient_id) x ON x.mid=a.id WHERE a.level='High'")->fetchColumn(),'icu'=>$pdo->query('SELECT COUNT(*) FROM ventilator_cases')->fetchColumn()];
app_header('Doctor Dashboard','doctor','dashboard'); ?>
<div class="grid four">
  <a class="card stat stat-link" href="stat-list.php?type=patients"><div><div class="label">Patients</div><div class="num"><?=$stats['patients']?></div><div class="open-label">กดดูรายชื่อผู้ป่วย</div></div><span class="badge">HN</span></a>
  <a class="card stat stat-link" href="stat-list.php?type=visits"><div><div class="label">Visits</div><div class="num"><?=$stats['visits']?></div><div class="open-label">กดดู Visit ทั้งหมด</div></div><span class="badge blue">Timeline</span></a>
  <a class="card stat stat-link" href="stat-list.php?type=high"><div><div class="label">High Risk</div><div class="num"><?=$stats['high']?></div><div class="open-label">กดดูว่าใครเสี่ยงสูง</div></div><span class="badge red">Risk</span></a>
  <a class="card stat stat-link" href="stat-list.php?type=icu"><div><div class="label">ICU</div><div class="num"><?=$stats['icu']?></div><div class="open-label">กดดูเคส ICU</div></div><span class="badge warn">Ventilator</span></a>
</div>
<div class="card" style="margin-top:18px"><div class="tl-head"><h3>ค้นหาผู้ป่วยด้วย HN</h3><a class="btn" href="register-patient.php">+ ลงทะเบียนคนไข้ใหม่</a></div><form><div class="row"><div class="field"><input name="hn" placeholder="เช่น HN000001" value="<?=e($q)?>"></div><div class="field"><button class="btn">ค้นหา</button></div></div></form><div class="table-wrap"><table class="table"><tr><th>HN</th><th>ชื่อ</th><th>เพศ/อายุ</th><th>BMI</th><th>โทร</th><th></th></tr><?php foreach($patients as $p):?><tr><td><b><?=e($p['hn'])?></b></td><td><?=e($p['first_name'].' '.$p['last_name'])?></td><td><?=e($p['sex'])?> / <?=e($p['age'])?></td><td><?=e($p['bmi'])?></td><td><?=e($p['phone'])?></td><td><a class="btn secondary" href="patient-profile.php?hn=<?=urlencode($p['hn'])?>">เปิดข้อมูล</a></td></tr><?php endforeach;?></table></div></div>
<?php app_footer(); ?>
