<?php require_once __DIR__.'/../../backend/shared/auth.php'; require_role('doctor'); require_once __DIR__.'/../../backend/shared/layout.php';
$hn=$_GET['hn']??''; $st=db()->prepare('SELECT * FROM patients WHERE hn=?'); $st->execute([$hn]); $p=$st->fetch(); if(!$p){http_response_code(404); exit('ไม่พบ HN');}
$c=db()->prepare('SELECT condition_name FROM patient_conditions WHERE patient_id=?'); $c->execute([$p['id']]); $conds=$c->fetchAll(PDO::FETCH_COLUMN);
$v=db()->prepare('SELECT * FROM visits WHERE patient_id=? ORDER BY visit_date DESC,id DESC LIMIT 3'); $v->execute([$p['id']]); $visits=$v->fetchAll();
$allCount=db()->prepare('SELECT COUNT(*) FROM visits WHERE patient_id=?'); $allCount->execute([$p['id']]); $count=$allCount->fetchColumn();
$r=db()->prepare('SELECT * FROM ai_risk_assessments WHERE patient_id=? ORDER BY assessed_at DESC LIMIT 1'); $r->execute([$p['id']]); $risk=$r->fetch();
app_header('ข้อมูลผู้ป่วย '.$p['hn'],'doctor','dashboard'); ?>
<a class="back" href="dashboard.php">← กลับ Dashboard</a><div class="grid two"><div class="card"><div class="tl-head"><h3><?=e($p['first_name'].' '.$p['last_name'])?></h3><span class="badge"><?=e($p['hn'])?></span></div><p class="tl-meta">เพศ <?=e($p['sex'])?> · อายุ <?=e($p['age'])?> ปี · BMI <?=e($p['bmi'])?></p><div class="chips"><?php foreach($conds as $co):?><span class="badge blue"><?=e($co)?></span><?php endforeach;?></div><p><b>แพ้ยา:</b> <?=e($p['allergy'])?></p><p><b>ข้อมูลเฉพาะทาง:</b> รอบเดือน <?=e($p['menstrual_history'])?> / ตั้งครรภ์ <?=e($p['pregnancy_history'])?></p><div class="actions"><a class="btn" href="add-treatment.php?hn=<?=urlencode($p['hn'])?>">+ เพิ่มการรักษา</a><a class="btn secondary" href="documents.php?hn=<?=urlencode($p['hn'])?>">ออกเอกสาร/PDF</a><a class="btn secondary" href="ai-risk.php?hn=<?=urlencode($p['hn'])?>&run=1">วิเคราะห์ AI</a><a class="btn secondary" href="icu.php?hn=<?=urlencode($p['hn'])?>">ICU</a></div></div><div class="card riskbox"><h3>AI Risk ล่าสุด</h3><?php if($risk):?><div class="tl-head"><span class="badge <?=$risk['level']==='High'?'red':($risk['level']==='Moderate'?'warn':'')?>"><?=e($risk['level'])?></span><b><?=$risk['score']?>/100</b></div><div class="riskbar"><span style="width:<?=$risk['score']?>%"></span></div><p><?=e($risk['recommendation'])?></p><?php else:?><p class="tl-meta">ยังไม่มีผลวิเคราะห์ กด “วิเคราะห์ AI” เพื่อประเมินจากข้อมูลล่าสุด</p><?php endif;?></div></div>
<div class="card" style="margin-top:18px"><div class="tl-head"><h3>Timeline การรับบริการล่าสุด</h3><span class="badge gray">แสดง 3 จาก <?=$count?></span></div><div class="timeline"><?php foreach($visits as $vv):?><div class="tl-item"><div class="tl-head"><div><div class="tl-title"><?=e($vv['visit_date'])?> · <?=e($vv['hospital_name'])?></div><div class="tl-meta"><?=e($vv['visit_type'])?> · <?=e($vv['department'])?> · <?=e($vv['ward'])?> · แพทย์ <?=e($vv['doctor_name'])?></div></div><a class="btn secondary" href="visit-detail.php?id=<?=$vv['id']?>">ดูรายละเอียด</a></div><p><b>มาเพราะ:</b> <?=e($vv['chief_complaint'])?></p><p><b>วินิจฉัย:</b> <?=e($vv['diagnosis'])?></p></div><?php endforeach;?></div><?php if($count>3):?><a class="btn secondary" href="timeline.php?hn=<?=urlencode($p['hn'])?>">ดู Timeline เพิ่มเติม</a><?php endif;?></div>
<?php app_footer(); ?>
